---
deployment:
  branch: deploy
  tasks:
    - export DEPLOYPATH=~/public_html/sensasi2025.hmsisfoudinus.org
    - echo "🚀 Deploying from deploy branch..."
    - echo "🧹 Membersihkan direktori tujuan..."
    - /bin/rm -rf $DEPLOYPATH/*
    - echo "📁 Menyalin file dari repository ke public_html..."
    - /bin/cp -R * $DEPLOYPATH/
    - echo "✅ Deploy berhasil ke sensasi2025.hmsisfoudinus.org"
